package constants;

public class ConstantsSQL {
    //FILE
    public final static String UPDATE_FILE_PATH = "UPDATE TODO SET FILENAMETODO=?, PATH=? WHERE ID=?";

    //TODO
    public final static String ADD_NEW_TASK = "INSERT INTO todo(DATETODO, NAMETODO, STATUSTODO, FILENAMETODO, USERID, PATH, added_date) values (?,?,?,?,?,?,?)";
    public final static String EXPIRED = "UPDATE TODO SET STATUSTODO=4 WHERE STATUSTODO=1 AND DATETODO<CURRENT_DATE()";
    public final static String GET_TASKS_FOR_USER = "SELECT ID, DATETODO, NAMETODO, STATUSTODO, FILENAMETODO FROM TODO WHERE USERID=? AND STATUSTODO=1";
    public final static String GET_TASKS_BY_STATUS = "SELECT ID, DATETODO, NAMETODO, STATUSTODO, FILENAMETODO FROM TODO WHERE USERID=? AND STATUSTODO=?";
    public final static String GET_TASKS_FOR_DATE = "SELECT ID, DATETODO, NAMETODO, STATUSTODO, FILENAMETODO FROM TODO WHERE USERID=? AND STATUSTODO=? AND DATETODO=?";
    public final static String DELETE_TASK = "DELETE FROM TODO WHERE ID=?";
    public final static String EDIT_TASK = "UPDATE TODO SET DATETODO=?, NAMETODO=? WHERE ID=?";
    public final static String UPDATE_STATUS = "UPDATE TODO SET STATUSTODO=? WHERE ID=?";
    public final static String UPDATE_RECOVERY = "UPDATE TODO SET STATUSTODO=?, DATETODO=CURRENT_DATE() WHERE ID=?";
    public final static String GET_TASK_BY_ID = "SELECT ID, DATETODO, NAMETODO, STATUSTODO, FILENAMETODO FROM TODO WHERE ID=?";

    //User
    public final static String ADD_NEW_USER = "INSERT INTO USER (FIRSTNAME, LASTNAME, LOGIN, PASSWORD) VALUES(?, ?, ?, ?)";
    public final static String GET_USER_BY_LOGIN_PASSWORD = "SELECT * FROM user WHERE login=? and password=?";
    public final static String GET_ID_USER = "SELECT ID FROM user WHERE LOGIN=?";
}